name: Kudos for Code
description: "Supporting your open source team..."

inputs:
  destination:
    description: "Where to save the generated kudos. Options: artifact, pool"
    default: pool
    required: true
  github-token:
    description: A GITHUB_TOKEN with custom permissions.
  search-dir:
    description: "Root directory containing package.json"
    default: "."
    required: true    
  pool-id:
    description: "PoolId to save kudos to at external pool service."
    default: ""    
  node-dev-dependencies:
    description: Identify contributors from devDependecies (Node.js)
    default: "true"
  identify-type:
    description: How should we identify Kudos? (sbom, setler)
    default: "sbom"
  identify-checks:
    description: Which methods should we use to identify the kudos? (kudos,contributors,lang)
    default: "kudos,contributors,lang"
  identify-langs:
    description: Which languages should we search for? (nodejs)
    default: "nodejs"
  setler-keys: 
    # generate with `npx @loremlabs/setler wallet keys env --filter kudos`
    description: Setler Kudos Keys
    default: ""
  pool-storage-token:
    description: Pool Storage Token
    default: ""
  pool-endpoint:
    description: Pool Endpoint
    default: "https://api.semicolons.com"
  skip-main-package:
    description: Don't create kudos for main package.
    default: "false"
  
runs:
  using: composite
  steps:
    - name: Set up action
      run: |
        echo "::group::Set up action"
        pnpm -C ${{ github.action_path }} install --no-optional
        pnpm --silent -C ${{ github.action_path }} build
        echo "${{ github.action_path }}/node_modules/.bin" >> $GITHUB_PATH
        echo "KUDOS_DIR=$(mkdir -p ../.kudos && cd ../.kudos;pwd)" >> $GITHUB_ENV
        echo "::endgroup::"
      shell: bash
    
    - name: Set up Required Tools
      if: contains(inputs.identify-type, 'sbom')
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .
        wget https://github.com/snyk/parlay/releases/download/v0.1.5/parlay_Linux_x86_64.tar.gz
        tar -xvf parlay_Linux_x86_64.tar.gz

    - name: Set up Kudos Tools
      run: |
        echo "::group::Set up Kudos tools"
        npx --yes @loremlabs/setler@latest echo version
        echo "::endgroup::"
      shell: bash

    - name: Set current cohort
      run: |
        echo "::group::Set current cohort"
        if [ -z "$USER_COHORT" ]; then
          echo "KUDOS_COHORT=$(date +'%Y%W')" >> $GITHUB_ENV
        else
          echo "KUDOS_COHORT=$USER_COHORT" >> $GITHUB_ENV
        fi
        echo "::endgroup::"
      env:
        USER_COHORT: ${{ inputs.cohort }}
      shell: bash

    - name: Set up Kudos Variables
      run: |
        echo "::group::Set up Kudos Variables"
        echo "KUDOS_OUTFILE=${{ env.KUDOS_DIR }}/${{ env.KUDOS_COHORT }}.ndjson" >> $GITHUB_ENV
        echo "::endgroup::"
      shell: bash

    - name: Check requirements
      if: contains(inputs.destination, 'pool')
      run: |
        echo "::group::Check requirements"

        if [ -z "${{ inputs.pool-id }}" ]; then
          echo "Missing input: pool-id"
          exit 1
        fi
        if [ -z "${{ inputs.setler-keys }}" ]; then
          echo "Missing input: setler-keys"
          exit 1
        fi
        if [ -z "${{ inputs.pool-storage-token }}" ]; then
          echo "Missing input: pool-storage-token"
          exit 1
        fi

        echo "::endgroup::"
      shell: bash

    - name: Download last artifact
      if: contains(inputs.destination, 'artifact')      
      # Not using actions/download-artifact as it doesn't let us specify the "source" of artifact.
      uses: dawidd6/action-download-artifact@v2
      with:
        name: kudos
        path: ${{ env.KUDOS_DIR }}
        branch: ${{ github.event.repository.default_branch }}
        workflow_conclusion: success
        event: push
        github_token: ${{ inputs.github-token || github.token }}
        if_no_artifact_found: warn

    - name: "Identify Contributors - Setler"
      if: contains(inputs.identify-type, 'setler')
      run: |
        echo "::group::Identify Contributors"

        npx @loremlabs/setler@latest kudos identify ${{ inputs.search-dir }} --outFile="${{ env.KUDOS_OUTFILE }}" ${{ inputs.skip-main-package != 'false' && '--skipMainPackage' }} ${{ inputs.node-dev-dependencies != 'false' && '--nodeDevDependencies' }} --checks=${{ inputs.identify-checks }} --lang=${{ inputs.identify-langs }}

        echo "::endgroup::"
      shell: bash

    - name: "Identify Contributors - SBOM"
      if: contains(inputs.identify-type, 'sbom')
      run: |
        echo "::group::Identify Contributors"

        ./scripts/get-repos-from-sbom.sh > "${{ env.KUDOS_OUTFILE }}"

        echo "::endgroup::"
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: contains(inputs.destination, 'artifact')      
      with:
        name: kudos
        path: ${{ env.KUDOS_DIR }}

    - name: Ink Kudos via Pool
      if: contains(inputs.destination, 'pool')
      env:
        SETLER_KEYS_0: ${{ inputs.setler-keys }}
        KUDOS_STORAGE_TOKEN: ${{ inputs.pool-storage-token }}
      run: |
        echo "::group::Ink Kudos via Pool"

        npx @loremlabs/setler@latest pool ink --poolId="${{ inputs.pool-id }}" --inFile="${{ env.KUDOS_OUTFILE }}" --poolEndpoint="${{ inputs.pool-endpoint }}"

        echo "::endgroup::"
      shell: bash

branding:
  icon: users
  color: gray-dark
